"""Render the dom0 qrexec policy that lets a management VM drive Qubes 4.3
Ansible (the official ``qubes-ansible`` collections).

This is the Ansible-side complement to the hexagon integration-test policy in
``qubes/policy.d/30-hexagon-test.policy``: it grants a *ManagementVM* the Admin
API + qrexec services the ``qubesos.core`` modules and the
``qubesos.security.qubes_proxy`` strategy need. Provisioning (qube lifecycle)
stays with hexagon proper; Ansible only enforces config *inside* qubes.

The policy body lives in a single Jinja2 template (``POLICY_TEMPLATE``) so the
whole grant set is readable top-to-bottom; rendering is pure -- no Qubes, no
I/O -- so it works anywhere and is unit-tested offline. The ``hexagon policy``
subcommand prints the result for review before it's applied in dom0.

Security model (mirrors the upstream ``30-mgmtvm.policy``):

  * Every grant is sourced from the concrete ManagementVM (``--mgmtvm``), never
    a broad ``@anyvm`` -- removing/renaming that qube is the kill-switch.
  * The MgmtVM may create qubes and *fully* manage only the ones it created,
    scoped by the unforgeable ``created-by-<mgmtvm>`` tag Qubes stamps on them.
  * ``qubes_proxy`` spins a disposable management VM per target so dom0 never
    parses untrusted playbook data (QubesOS/qubes-issues#10030); the
    ``qubes.AnsibleVM`` / ``qubes.Filecopy`` / dynamic-policy grants ride the
    same ``created-by`` tag.
"""

import socket

# Resolve the hostname at import time so `hexagon policy` prints a policy scoped
# to **this** machine rather than some conventionally-named qube.
DEFAULT_MGMTVM = socket.gethostname()
DEFAULT_MGMT_DISPVM = "default-mgmt-dvm"
DEFAULT_TEMPLATES = ["fedora-43-xfce", "debian-13-xfce"]
DEFAULT_SYS_VMS = ["sys-net", "sys-firewall", "sys-usb"]

# Column width for the service name in a rendered rule; the widest service we
# emit is ``ansible.CreateManagementPolicies`` (32). The ``rule`` macro pads to
# this so the columns line up regardless of service length.
_SVC_W = 32

# One editable source of truth for the whole policy. The ``rule`` macro renders
# a single qrexec line (SERVICE ARG SOURCE TARGET ACTION), padding SERVICE/ARG
# so columns align. ``created`` is the unforgeable created-by-<mgmtvm> tag.
POLICY_TEMPLATE = """\
{%- macro rule(svc, source, target, action, arg='*') -%}
{{ '%-*s'|format(svc_w, svc) }}  {{ '%-17s'|format(arg) }}  {{ source }}  {{ target }}  {{ action }}
{% endmacro -%}
# 30-mgmtvm.policy -- qrexec grants for Qubes 4.3 Ansible (qubes-ansible).
# Generated by `hexagon policy`; apply in dom0 (one-time):
#     sudo tee /etc/qubes/policy.d/30-mgmtvm.policy < this-output
#     qubes-policy-lint /etc/qubes/policy.d/30-mgmtvm.policy
#
# Source of every grant: {{ mgmtvm }} (rename/remove the qube to revoke).
# Full management is scoped to qubes tagged created-by-{{ mgmtvm }}.
#
# Columns:  SERVICE  ARGUMENT  SOURCE  TARGET  ACTION [params]

# --- Qube lifecycle: create any, manage only self-created ---
{{ rule('admin.vm.Create.AppVM', mgmtvm, 'dom0', 'allow') -}}
{{ rule('admin.vm.Create.StandaloneVM', mgmtvm, 'dom0', 'allow') -}}
{{ rule('admin.vm.Create.TemplateVM', mgmtvm, 'dom0', 'allow') -}}
{{ rule('admin.vm.Remove', mgmtvm, created, 'allow target=dom0') }}
# --- Clone base templates (StandaloneVM / new TemplateVM creation) ---
{% for tmpl in templates -%}
{{ rule('admin.vm.volume.CloneFrom', mgmtvm, tmpl, 'allow target=dom0') -}}
{% endfor %}

# --- Device enumeration + assignment (qubesos.core.host_devices_facts) ---
{{ rule('admin.vm.device.pci.Available', mgmtvm, 'dom0', 'allow') -}}
{{ rule('admin.vm.device.block.Available', mgmtvm, 'dom0', 'allow') -}}
{{ rule('admin.vm.device.pci.Assign', mgmtvm, created, 'allow target=dom0') }}
# --- Read the sys/template qubes the qube module inspects ---
{% for vm in sys_vms + templates -%}
{{ rule('admin.vm.property.Get', mgmtvm, vm, 'allow target=dom0') -}}
{% endfor %}

# --- qubes_proxy: per-target disposable management VM (dom0 isolation) ---
{{ rule('admin.vm.Create.DispVM', mgmtvm, 'dom0', 'allow', arg='+' ~ mgmt_dispvm) -}}
{{ rule('admin.vm.property.Get', mgmtvm, mgmt_dispvm, 'allow target=dom0', arg='+label') -}}
{{ rule('ansible.CreateManagementPolicies', mgmtvm, created, 'allow target=dom0') -}}
{{ rule('ansible.RemoveManagementPolicies', mgmtvm, created, 'allow target=dom0') -}}
{{ rule('qubes.AnsibleVM', mgmtvm, created, 'allow') -}}
{{ rule('qubes.Filecopy', mgmtvm, created, 'allow') -}}
"""


def render_policy(
    mgmtvm=DEFAULT_MGMTVM,
    templates=None,
    sys_vms=None,
    mgmt_dispvm=DEFAULT_MGMT_DISPVM,
):
    """Render ``/etc/qubes/policy.d/30-mgmtvm.policy`` for ``mgmtvm``.

    :param mgmtvm: the qube running ``ansible-playbook`` (source of every grant).
    :param templates: base templates the MgmtVM may clone / read (for
        StandaloneVM/TemplateVM creation and netvm existence checks).
    :param sys_vms: sys-* qubes whose properties the ``qube`` module must read
        (e.g. verifying a netvm exists and provides network).
    :param mgmt_dispvm: the management DispVM template ``qubes_proxy`` derives
        each target's disposable from.
    :returns: the policy file body, ready to write to dom0.
    """
    templates = list(templates) if templates is not None else list(DEFAULT_TEMPLATES)
    sys_vms = list(sys_vms) if sys_vms is not None else list(DEFAULT_SYS_VMS)

    try:
        import jinja2
    except ImportError as exc:
        raise RuntimeError(
            "jinja2 is required for the 'hexagon policy' command. "
            "Install it with: dnf install python3-jinja2"
        ) from exc

    template = jinja2.Template(
        POLICY_TEMPLATE, trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True
    )
    return template.render(
        mgmtvm=mgmtvm,
        templates=templates,
        sys_vms=sys_vms,
        mgmt_dispvm=mgmt_dispvm,
        created="@tag:created-by-{}".format(mgmtvm),
        svc_w=_SVC_W,
    )
