"""Render the dom0 qrexec policies a management VM needs. Two, for two jobs;
they coexist in ``/etc/qubes/policy.d/``:

  * ``render_policy`` / ``hexagon policy`` -- lets the MgmtVM drive Qubes 4.3
    Ansible (the official ``qubes-ansible`` collections): the Admin API +
    qrexec services the ``qubesos.core`` modules and the
    ``qubesos.security.qubes_proxy`` strategy need. Provisioning (qube
    lifecycle) stays with hexagon proper; Ansible only enforces config *inside*
    qubes. The two plain qrexec grants hexagon's own verbs need from that
    MgmtVM ride along on the same tags: ``qubes.VMShell`` (``hexagon reboot``
    powers a netvm off from inside when clients are attached) and
    ``qubes.StartApp`` (``hexagon terminal`` and ``reboot -t``).
  * ``render_test_policy`` / ``hexagon policy --test`` -- what the integration
    suite (docs/testing.md) needs from the qube it runs in: create test VMs,
    read everything, write only to VMs tagged ``hexagon-test``.

Each policy body is a single Jinja2 template so the whole grant set is readable
top-to-bottom; rendering is pure -- no Qubes, no I/O -- so it works anywhere
and is unit-tested offline. The subcommand prints the result for review before
it's applied in dom0.

Security model of the Ansible policy -- **tag-based**, so VMs opt in/out
without touching the policy:

  * **Source** of every grant is ``@tag:hexagon-admin`` -- the qube(s) running
    Ansible. Untag a qube (``qvm-tags <vm> del hexagon-admin``) and all its
    management power vanishes: the fleet-wide kill-switch.
  * **Managed** VMs are scoped by ``@tag:hexagon``. Opt a VM in with
    ``qvm-tags <vm> add hexagon``; remove the tag to exclude it. Management is
    never coupled to creation provenance or concrete names.
  * ``qubes_proxy`` spins a disposable management VM per target so dom0 never
    parses untrusted playbook data (QubesOS/qubes-issues#10030). Those
    ``disp-mgmt-*`` VMs are the ONE exception to the pure-tag model: the
    ``ansible.CreateManagementPolicies`` RPC hard-checks that they carry
    ``created-by-<calling-qube>`` (a concrete name Qubes auto-stamps), so their
    lifecycle grants are keyed on ``@tag:created-by-<admin>`` -- one admin qube
    name per entry in ``admin_qubes`` (default: the local host).
"""

import socket

# Tag defaults. Overridable from the CLI.
DEFAULT_ADMIN_TAG = "hexagon-admin"
DEFAULT_TARGET_TAG = "hexagon"
DEFAULT_MGMT_DISPVM = "default-mgmt-dvm"
DEFAULT_SYS_VMS = ["sys-net", "sys-firewall", "sys-usb"]

# The admin qube(s) whose disp-mgmt VMs need created-by grants. Defaults to the
# local host -- the common single-MgmtVM case. Multi-admin fleets pass more.
DEFAULT_ADMIN_QUBES = [socket.gethostname()]

# Column width for the service name in a rendered rule; the widest service we
# emit is ``ansible.CreateManagementPolicies`` (32). The ``rule`` macro pads to
# this so the columns line up regardless of service length.
_SVC_W = 32

# Tag on the VMs the integration suite creates; the test policy scopes the
# management qube's write access to it. tests/base.py re-imports this.
TEST_TAG = "hexagon-test"

# Shared by both templates: renders a single qrexec line (SERVICE ARG SOURCE
# TARGET ACTION), padding SERVICE/ARG so columns align.
_RULE_MACRO = """\
{%- macro rule(svc, source, target, action, arg='*') -%}
{{ '%-*s'|format(svc_w, svc) }}  {{ '%-19s'|format(arg) }}  {{ source }}  {{ target }}  {{ action }}
{% endmacro -%}
"""

# One editable source of truth for the whole Ansible policy. ``admin`` is
# @tag:hexagon-admin (source); ``target`` is @tag:hexagon (managed VMs).
POLICY_TEMPLATE = (
    _RULE_MACRO
    + """\
# 30-mgmtvm.policy -- qrexec grants for Qubes 4.3 Ansible (qubes-ansible).
# Generated by `hexagon policy`; apply in dom0 (one-time):
#     sudo tee /etc/qubes/policy.d/30-mgmtvm.policy < this-output
#     qubes-policy-lint /etc/qubes/policy.d/30-mgmtvm.policy
#
# Tag-based, so membership is a `qvm-tags` away:
#   - SOURCE of every grant: {{ admin }}
#       enroll a MgmtVM:  qvm-tags <vm> add {{ admin_tag }}   (untag = kill-switch)
#   - MANAGED VMs:           {{ target }}
#       opt a VM in:      qvm-tags <vm> add {{ target_tag }}  (untag = exclude)
#
# Columns:  SERVICE  ARGUMENT  SOURCE  TARGET  ACTION [params]

# --- Visibility: list + read managed qubes. admin.vm.List needs TWO rules: the
#     call is directed at dom0 (@adminvm), and qubesd then filters the returned
#     list PER-VM, so a rule matching each managed VM is also required or
#     `app.domains.get(<host>)` returns None ("Host not found").
{{ rule('admin.vm.List', admin, '@adminvm', 'allow target=dom0') -}}
{{ rule('admin.vm.List', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.CurrentState', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.property.Get', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.property.List', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.feature.Get', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.feature.CheckWithTemplate', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.tag.Get', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.tag.List', admin, target, 'allow target=dom0') }}
# --- Qube lifecycle: create any, manage only @tag:{{ target_tag }} VMs ---
{{ rule('admin.vm.Create.AppVM', admin, 'dom0', 'allow') -}}
{{ rule('admin.vm.Create.StandaloneVM', admin, 'dom0', 'allow') -}}
{{ rule('admin.vm.Create.TemplateVM', admin, 'dom0', 'allow') -}}
{{ rule('admin.vm.Start', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.Shutdown', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.Kill', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.Remove', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.property.Set', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.feature.Set', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.tag.Set', admin, target, 'allow target=dom0') -}}
{{ rule('admin.vm.tag.Remove', admin, target, 'allow target=dom0') }}
# --- hexagon CLI, run from the same MgmtVM. Plain qrexec calls INTO the managed
#     VM (no target=dom0 redirect, or they'd run in dom0):
#       qubes.VMShell   `hexagon reboot` runs `sudo poweroff` inside a netvm
#                       that has clients attached (refused -> 30s poll, kill);
#                       the VMShell prologue also reads feature.CheckWithTemplate
#                       (granted above)
#       qubes.StartApp  `hexagon terminal` / `reboot -t` opens a terminal (refused -> exit 1)
{{ rule('qubes.VMShell', admin, target, 'allow') -}}
{{ rule('qubes.StartApp', admin, target, 'allow', arg='+qubes-run-terminal') }}
# --- Clone base templates: tag any TemplateVM @tag:{{ target_tag }} to permit
#     cloning it (StandaloneVM / new TemplateVM creation). No name list -- the
#     managed tag doubles as the "cloneable source" tag. Reads on these are
#     already granted by the visibility block above (same tag).
{{ rule('admin.vm.volume.CloneFrom', admin, target, 'allow target=dom0') }}
# --- Device enumeration + assignment (qubesos.core.host_devices_facts) ---
{{ rule('admin.vm.device.pci.Available', admin, 'dom0', 'allow') -}}
{{ rule('admin.vm.device.block.Available', admin, 'dom0', 'allow') -}}
{{ rule('admin.vm.device.pci.Assign', admin, target, 'allow target=dom0') }}
# --- Read the sys qubes the qube module inspects (netvm existence/provides-net
#     checks). These aren't @tag:{{ target_tag }} (you don't manage sys-net), so
#     they stay explicit. Managed VMs + templates are already readable via the
#     visibility block. ---
{% for vm in sys_vms -%}
{{ rule('admin.vm.property.Get', admin, vm, 'allow target=dom0') -}}
{% endfor %}

# --- qubes_proxy: per-target disposable management VM (dom0 isolation) ---
# The proxy creates/starts/kills a disp-mgmt-* disposable, copies the play to
# it (Filecopy), runs it there (AnsibleVM), and has dom0 author ephemeral
# disp-mgmt->target VMRootShell/Filecopy rules via the CreateManagementPolicies
# RPC (so those are NOT emitted here). That RPC is invoked as
#     qrexec-client-vm <managed-vm> ansible.CreateManagementPolicies+<disposable>
# i.e. its qrexec TARGET is the MANAGED VM (@tag:{{ target_tag }}); dom0 then
# hard-checks that the ARGUMENT disposable carries created-by-<calling-qube>
# (Qubes auto-stamps it). Everything else in this block acts ON the disposable,
# so it keys on each admin qube's created-by tag -- one block per admin.
{{ rule('admin.vm.Create.DispVM', admin, 'dom0', 'allow', arg='+' ~ mgmt_dispvm) -}}
{{ rule('admin.vm.property.Get', admin, mgmt_dispvm, 'allow target=dom0', arg='+label') -}}
{{ rule('ansible.CreateManagementPolicies', admin, target, 'allow target=dom0') -}}
{{ rule('ansible.RemoveManagementPolicies', admin, target, 'allow target=dom0') -}}
{% for aq in admin_qubes %}
{% set created = '@tag:created-by-' ~ aq -%}
{{ rule('admin.vm.List', admin, created, 'allow target=dom0') -}}
{{ rule('admin.vm.CurrentState', admin, created, 'allow target=dom0') -}}
{{ rule('admin.vm.property.Get', admin, created, 'allow target=dom0') -}}
{{ rule('admin.vm.property.Set', admin, created, 'allow target=dom0') -}}
{{ rule('admin.vm.feature.Set', admin, created, 'allow target=dom0') -}}
{{ rule('admin.vm.Start', admin, created, 'allow target=dom0') -}}
{{ rule('admin.vm.Kill', admin, created, 'allow target=dom0') -}}
{{ rule('admin.vm.Remove', admin, created, 'allow target=dom0') -}}
{{ rule('qubes.AnsibleVM', admin, created, 'allow') -}}
{{ rule('qubes.Filecopy', admin, created, 'allow') -}}
{% endfor -%}
"""
)

# The integration-test policy. Source is the concrete management qube (one
# block per qube); writes are scoped to @tag:hexagon-test, bootstrapped by the
# created-by-<qube> tag Qubes stamps on every VM that qube creates.
TEST_POLICY_TEMPLATE = (
    _RULE_MACRO
    + """\
# 30-hexagon-test.policy -- qrexec grants for the hexagon integration tests.
# Generated by `hexagon policy --test`; apply in dom0 (one-time):
#     sudo tee /etc/qubes/policy.d/30-hexagon-test.policy < this-output
#     qubes-policy-lint /etc/qubes/policy.d/30-hexagon-test.policy
# Remove the file to revoke all access. Coexists with 30-mgmtvm.policy.
#
# Model: the management qube may CREATE test VMs and has full control over only
# the VMs tagged "{{ test_tag }}". qubesd stamps every VM it creates with
# "created-by-<qube>"; that alone unlocks applying the "{{ test_tag }}" tag, and
# from then on the tag-scoped rules cover everything.
#
# Columns:  SERVICE  ARGUMENT  SOURCE  TARGET  ACTION [params]
# "@adminvm" is dom0; admin calls execute there, hence "target=@adminvm".
{% for mq in admin_qubes %}
{% set created = '@tag:created-by-' ~ mq %}

# ===== management qube: {{ mq }} =====
# --- Create test VMs (global scope: the VM doesn't exist yet) ---
{{ rule('admin.vm.Create.AppVM', mq, '@adminvm', 'allow target=@adminvm') }}
# --- Read-only introspection of all VMs (the `hexagon ls` path enumerates every
#     domain and reads its tags/features/properties). admin.vm.List needs TWO
#     rules: the call is directed at dom0, so it needs a rule matching @adminvm;
#     qubesd then filters the returned list per-VM, so an @anyvm rule is also
#     required for templates / other VMs to be visible at all. ---
{{ rule('admin.vm.List', mq, '@adminvm', 'allow target=@adminvm') -}}
{{ rule('admin.vm.List', mq, '@anyvm', 'allow target=@adminvm') -}}
{{ rule('admin.label.List', mq, '@adminvm', 'allow target=@adminvm') -}}
{{ rule('admin.pool.List', mq, '@adminvm', 'allow target=@adminvm') -}}
{% for svc in ('admin.vm.property.Get', 'admin.vm.feature.Get',
               'admin.vm.feature.CheckWithTemplate',
               'admin.vm.tag.Get', 'admin.vm.tag.List') -%}
{{ rule(svc, mq, '@anyvm', 'allow target=@adminvm') -}}
{{ rule(svc, mq, '@adminvm', 'allow target=@adminvm') -}}
{% endfor %}
# --- Bootstrap: tag VMs we just created with "{{ test_tag }}". This is the
#     qube's ONLY tag power: one fixed tag, only on its own creations. qubesd
#     reserves no tag names, so a wildcard tag.Set on test VMs would let one be
#     tagged into another policy's source set (e.g. hexagon-admin). ---
{{ rule('admin.vm.tag.Set', mq, created, 'allow target=@adminvm', arg='+' ~ test_tag) }}
# --- Manage our test VMs, scoped by the tag (explicit services; no wildcard).
#     CurrentState is required: qubesadmin maps a refused call to power state
#     "NA", so without it is_running() is silently False and reboot + teardown
#     misbehave. ---
{% for svc in ('admin.vm.CurrentState', 'admin.vm.Start', 'admin.vm.Shutdown',
               'admin.vm.Kill', 'admin.vm.Remove',
               'admin.vm.property.Set', 'admin.vm.feature.Set') -%}
{{ rule(svc, mq, target, 'allow target=@adminvm') -}}
{% endfor %}
# --- Plain qrexec calls INTO test VMs (no target= redirect). qubes.VMShell: a
#     netvm reboot with clients attached runs `sudo poweroff` inside the VM.
#     qubes.StartApp: `hexagon terminal` / `reboot -t` opens a terminal; hexagon exits
#     non-zero if that's refused, so the suite doubles as a check of this grant. ---
{{ rule('qubes.VMShell', mq, target, 'allow') -}}
{{ rule('qubes.StartApp', mq, target, 'allow', arg='+qubes-run-terminal') }}
{% endfor -%}
"""
)


def render_policy(
    admin_tag=DEFAULT_ADMIN_TAG,
    target_tag=DEFAULT_TARGET_TAG,
    admin_qubes=None,
    sys_vms=None,
    mgmt_dispvm=DEFAULT_MGMT_DISPVM,
):
    """Render ``/etc/qubes/policy.d/30-mgmtvm.policy``.

    :param admin_tag: tag on qube(s) allowed to drive Ansible (grant SOURCE).
    :param target_tag: tag on managed qubes (grant TARGET). Also the "cloneable
        source" tag: tag a TemplateVM ``@tag:<target_tag>`` to permit cloning it.
    :param admin_qubes: concrete admin qube names whose ``disp-mgmt-*`` VMs need
        ``created-by-<name>`` grants (the qubes_proxy exception to pure tags).
        Defaults to the local host.
    :param sys_vms: sys-* qubes whose properties the ``qube`` module must read
        (e.g. verifying a netvm exists and provides network). These aren't
        managed, so they can't ride the target tag and stay explicit.
    :param mgmt_dispvm: the management DispVM template ``qubes_proxy`` derives
        each target's disposable from.
    :returns: the policy file body, ready to write to dom0.
    """
    admin_qubes = list(admin_qubes) if admin_qubes is not None else list(DEFAULT_ADMIN_QUBES)
    sys_vms = list(sys_vms) if sys_vms is not None else list(DEFAULT_SYS_VMS)
    return _render(
        POLICY_TEMPLATE,
        admin_tag=admin_tag,
        target_tag=target_tag,
        admin="@tag:{}".format(admin_tag),
        target="@tag:{}".format(target_tag),
        admin_qubes=admin_qubes,
        sys_vms=sys_vms,
        mgmt_dispvm=mgmt_dispvm,
    )


def render_test_policy(admin_qubes=None):
    """Render ``/etc/qubes/policy.d/30-hexagon-test.policy``.

    What the integration suite (docs/testing.md) needs from the management
    qube(s) it runs in: create test VMs, read everything, write only to VMs
    tagged ``TEST_TAG``. Its sole tag power is applying that one tag to VMs
    qubesd stamped ``created-by-<qube>``, so a stray run can never touch a
    real qube, and a test VM can never be tagged into another policy's grants.

    :param admin_qubes: management qube name(s), the grant SOURCE. Defaults to
        the local host: render it in the qube that runs the tests.
    :returns: the policy file body, ready to write to dom0.
    """
    admin_qubes = list(admin_qubes) if admin_qubes is not None else list(DEFAULT_ADMIN_QUBES)
    return _render(
        TEST_POLICY_TEMPLATE,
        admin_qubes=admin_qubes,
        test_tag=TEST_TAG,
        target="@tag:{}".format(TEST_TAG),
    )


def _render(source, **context):
    try:
        import jinja2
    except ImportError as exc:
        raise RuntimeError(
            "jinja2 is required for the 'hexagon policy' command. "
            "Install it with: dnf install python3-jinja2"
        ) from exc

    template = jinja2.Template(
        source, trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True
    )
    return template.render(svc_w=_SVC_W, **context)
