#!/bin/bash
# Builds RPM for installation in dom0.
# RPM is fully reproducible.
set -e
set -u
set -o pipefail


if [[ -n "${VIRTUAL_ENV:-}" ]]; then
    echo "ERROR: unset VIRTUAL_ENV. Using a virtualenv interferes with package reproducibility."
    exit 1
fi

# Prepare tarball, rpmbuild will use it
mkdir -p dist/
rm -f dist/*.tar.gz
rm -f rpm-build/RPMS/noarch/*.rpm
/usr/bin/python3 setup.py sdist

# Use the epoch time of the highest semver tag available.
# SOURCE_DATE_EPOCH="$(git tag | sort -V | tail -n 1 | xargs git log -1 --format=%at)"
# Use the epoch time of the most recent commit. If works in dev,
# as well as building from signed tags.
SOURCE_DATE_EPOCH="$(git log -1 --format=%at HEAD)"
export SOURCE_DATE_EPOCH

# Place tarball where rpmbuild will find it
cp dist/*.tar.gz rpm-build/SOURCES/

# Build for Qubes 4.0.x and 4.1.x, for which dom0 is based on
# F25 and F32, respectively.
for i in 25 32; do
    # dom0 defaults to python3.5 in F25
    python_version="python3.5"
    if [[ $i = 32 ]]; then
        python_version="python3.8"
    fi
    dist=".fc${i}"
    rpmbuild \
        --quiet \
        --define "_topdir $PWD/rpm-build" \
        --define "dist $dist" \
        --define "_python_version $python_version" \
        -bb --clean "rpm-build/SPECS/hexagon.spec"
done

printf '\nBuild complete! RPMs and their checksums are:\n\n'
find rpm-build/ -type f -iname '*.rpm' -print0 | sort -zV | xargs -0 sha256sum
